Fix existing branch detection for PR creation
When we try to create a PR for changes to the design system or React
components our GitHub workflow fails with the error

Fetching the repository
  /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +ee3f87c88500f28a0cc9baf4101cc39beb7924ad:refs/remotes/origin/develop
  remote: Duplicate header: "Authorization"
  Error: fatal: unable to access 'https://github.com/danskernesdigitalebibliotek/dpl-cms/': The requested URL returned error: 400

This seems to be caused by the update to actions/checkout@v6.
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2906

The action we currently use, GuillaumeFalourd/branch-exists, does not
seem to be well supported so replace it with standard git commands.

Use ls-remote to check the existence of a branch on the origin
instead of what has been checked out locally.