Downgrade to Lighthouse CI 0.9 to fix report uploads
Lighthouse CI/lhci 0.10 introduces a change where it will respect the
HTTP_PROXY url environment variable for API requests. Apparently this
includes uploading reports to temporary storage.
https://github.com/GoogleChrome/lighthouse-ci/releases/tag/v0.10.0
https://github.com/GoogleChrome/lighthouse-ci/pull/727

As we setup Wiremock as a general HTTP proxy for Lighthouse requests to
mock API requests, report uploads will also pass through Wiremock.
This results in an error when uploading reports:

FetchError: request to https://us-central1-lighthouse-infrastructure.cloudfunctions.net/saveHtmlReport failed, reason: self signed certificate in certificate chain

To address this we either need to move away from browser proxying so
we only use WireMock for specific external systems or setup the browser
proxy to provide a trusted certificate chain.
https://wiremock.org/docs/proxying/#browser-proxying-of-https